alter table SALES_BOOKING_ITEM add constraint FK_SALES_BOOKING_ITEM_ON_BOOKING foreign key (BOOKING_ID) references SALES_BOOKING(ID);
alter table SALES_BOOKING_ITEM add constraint FK_SALES_BOOKING_ITEM_ON_SHOW_DATE foreign key (SHOW_DATE_ID) references SALES_SHOW_DATE(ID);
create index IDX_SALES_BOOKING_ITEM_ON_BOOKING on SALES_BOOKING_ITEM (BOOKING_ID);
create index IDX_SALES_BOOKING_ITEM_ON_SHOW_DATE on SALES_BOOKING_ITEM (SHOW_DATE_ID);
