alter table SALES_BOOKING add constraint FK_SALES_BOOKING_ON_CUSTOMER foreign key (CUSTOMER_ID) references SALES_CUSTOMER(ID);
create index IDX_SALES_BOOKING_ON_CUSTOMER on SALES_BOOKING (CUSTOMER_ID);
