alter table SALES_BOOKING add constraint FK_SALES_BOOKING_ON_SHOW_DATE_TIME foreign key (SHOW_DATE_TIME_ID) references SALES_SHOW_DATE(ID);
create index IDX_SALES_BOOKING_ON_SHOW_DATE_TIME on SALES_BOOKING (SHOW_DATE_TIME_ID);
